image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_extension:
  stage: build
  script:
    - cd vscode-extension
    - npm install
    - npx vsce package
  artifacts:
    paths:
      - vscode-extension/chariot-lang-*.vsix

publish_extension:
  stage: deploy
  script:
    - |
      FILE="$(find vscode-extension/ -type f -name "chariot-lang-*.vsix")"
      curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file $FILE \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/my_package/${CI_COMMIT_TAG}/$(basename $FILE)"