image: node:latest

cache:
  paths:
    - node_modules/

build_extension:
  script:
    - cd vscode-extension
    - npm install
    - npx vsce package
  artifacts:
    paths:
      - vscode-extension/chariot-lang-*.vsix
