image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_extension:
  stage: build
  script:
    - cd vscode-extension
    - npm install
    - npx vsce package
  artifacts:
    paths:
      - vscode-extension/chariot-lang-*.vsix

publish_extension:
  stage: deploy
  script:
    - FILE_PATH="$(find vscode-extension/ -type f -name "chariot-lang-*.vsix")"
    - FILE_NAME="$(basename $FILE_PATH)"
    - |
      curl --location --user "gitlab-ci-token:$CI_JOB_TOKEN" --upload-file "$FILE_PATH" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/vscode_extension/${CI_COMMIT_SHA}/${FILE_NAME}"