[workspace]
resolver = "3"
members = [
    "rootfs",
    "runtime",
    "tools/rootfs_cli",
    "util",
]

[workspace.package]
version = "0.1.0"
authors = ["WuX"]

[workspace.dependencies]
chariot_rootfs = { path = "rootfs" }
chariot_runtime = { path = "runtime" }
chariot_util = { path = "util" }
nix = "0.31.2"
thiserror = "2.0.18"
