use std::{
    collections::{HashMap, HashSet},
    fs::{OpenOptions, exists, write},
    io::{self, ErrorKind, Seek, SeekFrom, Write},
    path::{Path, PathBuf},
    sync::Arc,
    time::Duration,
};

use chariot_runtime::{Mount, MountKind, Overlay, OverlayUpperDirectory, RuntimeError, runtime_execute};
use chariot_util::{
    fs::{FileSystemError, force_rm_contents, make_path},
    lock::{DirLock, LockShared},
    temp::TempDirProvider,
};
use reqwest::blocking::Client;
use tar::Archive;
use thiserror::Error;
use xz2::read::XzDecoder;

use crate::{db::Database, pkgset::CachedPkgSet};

mod db;
pub mod pkgset;

pub const ROOTFS_INIT_VERSION: &str = "2026/4/30";

const SETUP_SCRIPT: &str = r##"
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen

echo "Acquire::Check-Valid-Until \"false\";" > /etc/apt/apt.conf
echo "Binary::apt::APT::Keep-Downloaded-Packages \"true\";" >> /etc/apt/apt.conf
echo "APT::Install-Suggests \"false\";" >> /etc/apt/apt.conf
echo "APT::Install-Recommends \"false\";" >> /etc/apt/apt.conf
echo "APT::Sandbox::User \"root\";" >> /etc/apt/apt.conf
echo "Dpkg::Use-Pty \"false\";" >> /etc/apt/apt.conf
echo "Dir::Log::Terminal \"\";" >> /etc/apt/apt.conf
echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/unsafe-io

apt-get update
apt-get install -y locales
locale-gen

groupadd -g 1000 chariot
useradd -u 1000 -g 1000 -M -s /bin/bash chariot
passwd -l chariot
"##;

const ROOT_UID: u32 = 0;
const ROOT_GID: u32 = 0;
const USER_UID: u32 = 1000;
const USER_GID: u32 = 1000;

const CONFIG_KEY_VERSION: &str = "version";
const CONFIG_KEY_INIT_VERSION: &str = "init_version";

#[derive(Error, Debug)]
pub enum RootFSError {
    #[error(transparent)]
    FileSystem(#[from] FileSystemError),

    #[error(transparent)]
    Runtime(#[from] RuntimeError),

    #[error(transparent)]
    Database(#[from] rusqlite::Error),

    #[error("Failed to download native package `{}`", name)]
    DownloadPackage { name: String },

    #[error("Failed to install native package `{}`", name)]
    InstallPackage { name: String },

    #[error("RootFS database missing config key `{}`", key)]
    MissingConfigKey { key: String },
}

#[derive(Error, Debug)]
pub enum RootFSInitError {
    #[error(transparent)]
    FileSystem(#[from] FileSystemError),

    #[error(transparent)]
    Runtime(#[from] RuntimeError),

    #[error(transparent)]
    Http(#[from] reqwest::Error),

    #[error(transparent)]
    Database(#[from] rusqlite::Error),

    #[error("Failed to unpack tar archive `{}` to `{}`", archive.display(), to.display())]
    TarUnpack { archive: PathBuf, to: PathBuf, source: io::Error },

    #[error("Error during rootfs setup script")]
    SetupScript,

    #[error("Error during root package install")]
    RootPackageInstall,
}

#[derive(Error, Debug)]
pub enum RootFSGetError {
    #[error(transparent)]
    FileSystem(#[from] FileSystemError),

    #[error(transparent)]
    Database(#[from] rusqlite::Error),
}

pub struct RootFS {
    _lock: DirLock<LockShared>,
    path: PathBuf,
    db: Database,
    tempdir_provider: Arc<TempDirProvider>,
}

enum RootFSPath {
    Archive,
    Gitignore,
    Intact,
    Database,
    Fs,
    PackageSets,
    PackageSet(i64),
}

fn rootfs_shell(fs_path: impl AsRef<Path>, script: impl AsRef<str>, logger: &mut dyn Write) -> Result<i32, RuntimeError> {
    runtime_execute(
        fs_path,
        false,
        ROOT_UID,
        ROOT_GID,
        "/",
        &vec![],
        &vec![],
        &HashMap::<&str, &str>::new(),
        false,
        logger,
        vec!["bash", "-c", script.as_ref()],
    )
}

fn rootfs_sub_path(rootfs_path: impl AsRef<Path>, sub_path: RootFSPath) -> PathBuf {
    let base = rootfs_path.as_ref();
    match sub_path {
        RootFSPath::Archive => base.join("rootfs_archive.tar.xz"),
        RootFSPath::Gitignore => base.join(".gitignore"),
        RootFSPath::Intact => base.join(".intact"),
        RootFSPath::Database => base.join("rootfsdb.sqlite"),
        RootFSPath::Fs => base.join("fs"),
        RootFSPath::PackageSets => base.join("pkgsets"),
        RootFSPath::PackageSet(id) => base.join("pkgsets").join(id.to_string()),
    }
}

impl RootFS {
    /// Initialize a new rootfs. This will wipe the path provided.
    pub fn init(
        path: impl AsRef<Path>,
        tempdir_provider: Arc<TempDirProvider>,
        rootfs_version: impl AsRef<str>,
        root_packages: HashSet<impl AsRef<str>>,
        logger: &mut dyn Write,
    ) -> Result<Self, RootFSInitError> {
        make_path(&path)?;

        let rootfs_lock = DirLock::exclusive_noblock(&path)?;

        force_rm_contents(&path, None)?;

        let gitignore_path = rootfs_sub_path(&path, RootFSPath::Gitignore);
        write(&gitignore_path, "# Generated by Chariot\n*").map_err(|err| FileSystemError::WriteFile {
            path: gitignore_path.clone(),
            source: err,
        })?;

        for sub_path in [RootFSPath::Fs, RootFSPath::PackageSets] {
            make_path(rootfs_sub_path(&path, sub_path))?;
        }

        let archive_path = rootfs_sub_path(&path, RootFSPath::Archive);

        let mut archive_file = OpenOptions::new()
            .create_new(true)
            .write(true)
            .read(true)
            .open(&archive_path)
            .map_err(|err| FileSystemError::Open {
                path: archive_path.clone(),
                source: err,
            })?;

        let client = Client::builder().connect_timeout(Duration::from_secs(10)).build()?;
        client
            .get(&format!(
                "https://github.com/elysium-os/chariot-rootfs/releases/download/{}/rootfs-amd64.tar.xz",
                rootfs_version.as_ref()
            ))
            .send()?
            .error_for_status()?
            .copy_to(&mut archive_file)?;

        archive_file.seek(SeekFrom::Start(0)).map_err(|err| FileSystemError::SeekFile {
            path: archive_path.clone(),
            source: err,
        })?;

        let fs_path = rootfs_sub_path(&path, RootFSPath::Fs);

        let mut archive = Archive::new(XzDecoder::new(archive_file));
        archive.unpack(&fs_path).map_err(|err| RootFSInitError::TarUnpack {
            to: fs_path.clone(),
            archive: archive_path.clone(),
            source: err,
        })?;

        let exit_code = rootfs_shell(&fs_path, SETUP_SCRIPT, logger)?;
        if exit_code != 0 {
            return Err(RootFSInitError::SetupScript);
        }

        let exit_code = rootfs_shell(
            &fs_path,
            format!(
                "apt-get install -y {}",
                root_packages.iter().map(|pkg| pkg.as_ref()).collect::<Vec<&str>>().join(" ")
            ),
            logger,
        )?;
        if exit_code != 0 {
            return Err(RootFSInitError::RootPackageInstall);
        }

        let db = Database::connect(rootfs_sub_path(&path, RootFSPath::Database))?;

        db.insert_config_option(CONFIG_KEY_VERSION, rootfs_version)?;
        db.insert_config_option(CONFIG_KEY_INIT_VERSION, ROOTFS_INIT_VERSION)?;
        for pkg in root_packages {
            db.insert_root_pkg(pkg)?;
        }

        let intact_path = rootfs_sub_path(&path, RootFSPath::Intact);
        OpenOptions::new()
            .create(true)
            .write(true)
            .open(&intact_path)
            .map_err(|err| FileSystemError::Open {
                path: intact_path,
                source: err,
            })?;

        Ok(Self {
            _lock: rootfs_lock.relock_shared_noblock()?,
            path: path.as_ref().to_path_buf(),
            db,
            tempdir_provider,
        })
    }

    /// Get a `RootFS` for an already initialized rootfs.
    /// Returns `None` if the rootfs is not present or in an unknown state.
    pub fn get(path: impl AsRef<Path>, tempdir_provider: Arc<TempDirProvider>) -> Result<Option<Self>, RootFSGetError> {
        let cache_lock = match DirLock::shared(&path) {
            Err(FileSystemError::Open { source, .. }) if source.kind() == ErrorKind::NotFound => return Ok(None),
            Err(err) => return Err(err.into()),
            Ok(lock) => lock,
        };

        let intact_path = rootfs_sub_path(&path, RootFSPath::Intact);
        if !exists(&intact_path).map_err(|err| FileSystemError::Exists {
            path: intact_path,
            source: err,
        })? {
            return Ok(None);
        }

        let cache = Self {
            _lock: cache_lock,
            db: Database::connect(rootfs_sub_path(&path, RootFSPath::Database))?,
            path: path.as_ref().to_path_buf(),
            tempdir_provider,
        };

        Ok(Some(cache))
    }

    pub fn get_version(&self) -> Result<String, RootFSError> {
        match self.db.get_config_option(CONFIG_KEY_VERSION)? {
            Some(version) => Ok(version),
            None => Err(RootFSError::MissingConfigKey {
                key: String::from(CONFIG_KEY_VERSION),
            }),
        }
    }

    pub fn get_init_version(&self) -> Result<String, RootFSError> {
        match self.db.get_config_option(CONFIG_KEY_INIT_VERSION)? {
            Some(version) => Ok(version),
            None => Err(RootFSError::MissingConfigKey {
                key: String::from(CONFIG_KEY_INIT_VERSION),
            }),
        }
    }

    pub fn get_root_packages(&self) -> Result<HashSet<String>, RootFSError> {
        Ok(self.db.get_root_pkgs()?)
    }

    fn sub_path(&self, sub_path: RootFSPath) -> PathBuf {
        rootfs_sub_path(&self.path, sub_path)
    }

    fn download_native_package(&self, package: impl AsRef<str>, logger: &mut dyn Write) -> Result<(), RootFSError> {
        let exit_code = rootfs_shell(
            self.sub_path(RootFSPath::Fs),
            format!("apt-get install -y --download-only {}", package.as_ref()),
            logger,
        )?;

        if exit_code != 0 {
            return Err(RootFSError::DownloadPackage {
                name: package.as_ref().to_string(),
            });
        }

        Ok(())
    }

    fn install_native_package(&self, install_path: impl AsRef<Path>, package: impl AsRef<str>, logger: &mut dyn Write) -> Result<(), RootFSError> {
        let work_dir = self.tempdir_provider.get()?;

        let exit_code = runtime_execute(
            self.sub_path(RootFSPath::Fs),
            true,
            ROOT_UID,
            ROOT_GID,
            "/",
            &vec![&Mount {
                dest: PathBuf::new(),
                kind: MountKind::OverlayFS(Overlay {
                    upper_directory: Some(OverlayUpperDirectory {
                        upper_directory: install_path.as_ref().to_path_buf(),
                        work_directory: work_dir.path(),
                    }),
                    lower_directories: vec![self.sub_path(RootFSPath::Fs)],
                }),
            }],
            &vec![],
            &HashMap::<&str, &str>::new(),
            false,
            logger,
            vec!["bash", "-c", format!("apt-get install -y --no-download {}", package.as_ref()).as_str()],
        )?;

        if exit_code != 0 {
            return Err(RootFSError::InstallPackage {
                name: package.as_ref().to_string(),
            });
        }

        return Ok(());
    }

    pub fn exec(
        &self,
        cwd: impl AsRef<Path>,
        mounts: &Vec<&Mount>,
        environment: &HashMap<impl AsRef<str>, impl AsRef<str>>,
        logger: &mut dyn Write,
        args: Vec<impl AsRef<str>>,
        pkgset: &Option<CachedPkgSet>,
    ) -> Result<i32, RuntimeError> {
        let mut lower_mounts = Vec::new();
        if let Some(pkgset) = pkgset {
            lower_mounts.push(Mount {
                dest: PathBuf::new(),
                kind: MountKind::OverlayFS(Overlay {
                    upper_directory: None,
                    lower_directories: vec![self.sub_path(RootFSPath::Fs), pkgset.path()],
                }),
            });
        }

        runtime_execute(
            self.sub_path(RootFSPath::Fs),
            true,
            USER_UID,
            USER_GID,
            cwd,
            &lower_mounts.iter().collect(),
            mounts,
            environment,
            false,
            logger,
            args,
        )
    }
}
