use std::{
    collections::{HashMap, HashSet},
    fs::{rename, write},
    io::{self, Cursor, ErrorKind, Write},
    path::{Path, PathBuf},
    time::Duration,
};

use chariot_runtime::{Mount, MountKind, Overlay, OverlayUpperDirectory, RuntimeError, runtime_execute};
use chariot_util::{
    fs::{FileSystemError, force_rm, force_rm_contents, make_path},
    lock::{DirLock, LockShared},
};
use reqwest::blocking::Client;
use sha2::{Digest, Sha256};
use tar::Archive;
use thiserror::Error;
use xz2::read::XzDecoder;

use crate::{
    db::Database,
    manifest::{Manifest, ManifestFetchError},
    state::{State, StateReadError, StateWriteError},
};

pub use manifest::ManifestFetchSpec;
pub use pkgset::CachedPkgSet;

mod db;
mod manifest;
mod pkgset;
mod state;

const ROOTFS_VERSION: i64 = 1;

const PLACEHOLDER_ROOT_PACKAGES: &str = "@ROOT_PACKAGES@";
const PLACEHOLDER_PACKAGE: &str = "@PACKAGE@";

#[derive(Error, Debug)]
pub enum RootFSError {
    #[error(transparent)]
    FileSystem(#[from] FileSystemError),

    #[error(transparent)]
    Runtime(#[from] RuntimeError),

    #[error(transparent)]
    Database(#[from] rusqlite::Error),

    #[error("Failed to download native package `{}`", name)]
    DownloadPackage { name: String },

    #[error("Failed to install native package `{}`", name)]
    InstallPackage { name: String },
}

#[derive(Error, Debug)]
pub enum RootFSInitError {
    #[error(transparent)]
    FileSystem(#[from] FileSystemError),

    #[error(transparent)]
    Runtime(#[from] RuntimeError),

    #[error(transparent)]
    Http(#[from] reqwest::Error),

    #[error(transparent)]
    Database(#[from] rusqlite::Error),

    #[error("Failed to write state file")]
    StateWrite(#[from] StateWriteError),

    #[error("RootFS manifest fetch failed")]
    ManifestFetch(#[from] ManifestFetchError),

    #[error("RootFS setup command is missing root packages placeholder")]
    SetupMissingRootPackagesPlaceholder,

    #[error("Download command is missing package placeholder")]
    DownloadMissingPackagePlaceholder,

    #[error("Install command is missing package placeholder")]
    InstallMissingPackagePlaceholder,

    #[error("Failed to unpack tar archive to `{}`", to.display())]
    TarUnpack { to: PathBuf, source: io::Error },

    #[error("RootFS setup command exited with a non-zero code")]
    SetupScript,

    #[error("RootFS archive hash does not match expected hash, expected `{}`, got `{}`", expected, found)]
    ArchiveHashMismatch { expected: String, found: String },

    #[error("Invalid RootFS compression `{}`", .0)]
    InvalidRootFSCompression(String),

    #[error("Zstd error during RootFS decompression")]
    ZstdDecompression(#[source] io::Error),
}

#[derive(Error, Debug)]
pub enum RootFSGetError {
    #[error(transparent)]
    FileSystem(#[from] FileSystemError),

    #[error(transparent)]
    Database(#[from] rusqlite::Error),

    #[error("Failed to read state file")]
    StateRead(#[from] StateReadError),
}

pub struct RootFS {
    _lock: DirLock<LockShared>,
    path: PathBuf,
    db: Database,
    state: State,
}

enum RootFSPath {
    Gitignore,
    State,
    Database,
    Fs,
    FsTmp,
    PackageSets,
    PackageSet(i64),
    PackageSetWork,
}

fn rootfs_sub_path(rootfs_path: impl AsRef<Path>, sub_path: RootFSPath) -> PathBuf {
    let base = rootfs_path.as_ref();
    match sub_path {
        RootFSPath::Gitignore => base.join(".gitignore"),
        RootFSPath::State => base.join("state.toml"),
        RootFSPath::Database => base.join("rootfsdb.sqlite"),
        RootFSPath::Fs => base.join("fs"),
        RootFSPath::FsTmp => base.join(".fs_tmp"),
        RootFSPath::PackageSets => base.join("pkgsets"),
        RootFSPath::PackageSet(id) => base.join("pkgsets").join(id.to_string()),
        RootFSPath::PackageSetWork => base.join("pkgsets").join(".work"),
    }
}

impl RootFS {
    pub fn init(
        path: impl AsRef<Path>,
        manifest_spec: &ManifestFetchSpec,
        extra_root_packages: HashSet<impl AsRef<str>>,
        logger: &mut dyn Write,
    ) -> Result<Self, RootFSInitError> {
        let manifest = Manifest::fetch(&manifest_spec)?;

        if !manifest.commands.setup.contains(PLACEHOLDER_ROOT_PACKAGES) {
            return Err(RootFSInitError::SetupMissingRootPackagesPlaceholder);
        }

        if !manifest.commands.pkg_download.contains(PLACEHOLDER_PACKAGE) {
            return Err(RootFSInitError::DownloadMissingPackagePlaceholder);
        }

        if !manifest.commands.pkg_install.contains(PLACEHOLDER_PACKAGE) {
            return Err(RootFSInitError::InstallMissingPackagePlaceholder);
        }

        make_path(&path)?;
        let rootfs_lock = DirLock::exclusive_noblock(&path)?;
        force_rm_contents(&path, None)?;

        let gitignore_path = rootfs_sub_path(&path, RootFSPath::Gitignore);
        write(&gitignore_path, "# Generated by Chariot\n*").map_err(|err| FileSystemError::WriteFile {
            path: gitignore_path.clone(),
            source: err,
        })?;

        for sub_path in [RootFSPath::Fs, RootFSPath::PackageSets] {
            make_path(rootfs_sub_path(&path, sub_path))?;
        }

        let state = State {
            manifest: manifest_spec.clone(),
            extra_root_packages: extra_root_packages.iter().map(|str| str.as_ref().to_string()).collect(),
            root_packages: manifest.packages.root,
            package_bsdtar: manifest.packages.bsdtar,
            package_git: manifest.packages.git,
            package_patch: manifest.packages.patch,
            command_pkg_download: manifest.commands.pkg_download,
            command_pkg_install: manifest.commands.pkg_install,
            user_uid: manifest.ids.user_uid,
            user_gid: manifest.ids.user_gid,
            root_uid: manifest.ids.root_uid,
            root_gid: manifest.ids.root_gid,
        };

        state.write(rootfs_sub_path(&path, RootFSPath::State), false)?;

        let client = Client::builder().connect_timeout(Duration::from_secs(10)).build()?;
        let archive_data = client.get(manifest.rootfs.url).send()?.error_for_status()?.bytes()?;
        let archive_hash = {
            let mut hasher = Sha256::new();
            hasher.update(&archive_data);
            hex::encode(hasher.finalize())
        };

        if archive_hash != manifest.rootfs.hash {
            return Err(RootFSInitError::ArchiveHashMismatch {
                expected: manifest.rootfs.hash,
                found: archive_hash,
            });
        }

        let decompressor: &mut dyn io::Read = match manifest.rootfs.compression.as_str() {
            "xz" => &mut XzDecoder::new(Cursor::new(archive_data)),
            "zstd" => &mut zstd::Decoder::new(Cursor::new(archive_data)).map_err(|err| RootFSInitError::ZstdDecompression(err))?,
            _ => return Err(RootFSInitError::InvalidRootFSCompression(manifest.rootfs.compression)),
        };

        let fs_path = rootfs_sub_path(&path, RootFSPath::Fs);
        let fs_tmp_path = match manifest.rootfs.subdir {
            None => &fs_path,
            Some(_) => &rootfs_sub_path(&path, RootFSPath::FsTmp),
        };

        Archive::new(decompressor)
            .unpack(&fs_tmp_path)
            .map_err(|err| RootFSInitError::TarUnpack {
                to: fs_tmp_path.clone(),
                source: err,
            })?;

        if let Some(subdir) = manifest.rootfs.subdir {
            let from_path = fs_tmp_path.join(subdir);
            rename(&from_path, &fs_path).map_err(|err| FileSystemError::Rename {
                from: from_path.to_path_buf(),
                to: fs_path.to_path_buf(),
                source: err,
            })?;

            force_rm(fs_tmp_path)?;
        }

        let setup_command = manifest.commands.setup.replace(
            PLACEHOLDER_ROOT_PACKAGES,
            state
                .root_packages
                .iter()
                .map(|pkg| pkg.as_str())
                .chain(state.extra_root_packages.iter().map(|pkg| pkg.as_str()))
                .collect::<HashSet<_>>() // deduplicate via HashSet
                .into_iter()
                .collect::<Vec<_>>()
                .join(" ")
                .as_str(),
        );

        let exit_code = runtime_execute(
            rootfs_sub_path(&path, RootFSPath::Fs),
            false,
            state.root_uid,
            state.root_gid,
            "/",
            &vec![],
            &vec![],
            &HashMap::<&str, &str>::new(),
            false,
            logger,
            vec!["bash", "-c", &setup_command],
        )?;

        if exit_code != 0 {
            return Err(RootFSInitError::SetupScript);
        }

        let db = Database::connect(rootfs_sub_path(&path, RootFSPath::Database))?;

        state.write(rootfs_sub_path(&path, RootFSPath::State), true)?;

        Ok(Self {
            _lock: rootfs_lock.relock_shared_noblock()?,
            path: path.as_ref().to_path_buf(),
            db,
            state,
        })
    }

    pub fn get(path: impl AsRef<Path>) -> Result<Option<Self>, RootFSGetError> {
        let cache_lock = match DirLock::shared(&path) {
            Err(FileSystemError::Open { source, .. }) if source.kind() == ErrorKind::NotFound => return Ok(None),
            Err(err) => return Err(err.into()),
            Ok(lock) => lock,
        };

        let state = match State::read(rootfs_sub_path(&path, RootFSPath::State))? {
            None => return Ok(None),
            Some(state) => state,
        };

        let cache = Self {
            _lock: cache_lock,
            path: path.as_ref().to_path_buf(),
            db: Database::connect(rootfs_sub_path(&path, RootFSPath::Database))?,
            state,
        };

        Ok(Some(cache))
    }

    pub fn get_manifest_spec(&self) -> &ManifestFetchSpec {
        &self.state.manifest
    }

    pub fn get_extra_root_packages(&self) -> &HashSet<String> {
        &self.state.extra_root_packages
    }

    pub fn get_bsdtar_package(&self) -> &String {
        &self.state.package_bsdtar
    }

    pub fn get_git_package(&self) -> &String {
        &self.state.package_git
    }

    pub fn get_patch_package(&self) -> &String {
        &self.state.package_patch
    }

    fn sub_path(&self, sub_path: RootFSPath) -> PathBuf {
        rootfs_sub_path(&self.path, sub_path)
    }

    fn download_native_package(&self, package: impl AsRef<str>, logger: &mut dyn Write) -> Result<(), RootFSError> {
        let exit_code = runtime_execute(
            self.sub_path(RootFSPath::Fs),
            false,
            self.state.root_uid,
            self.state.root_gid,
            "/",
            &vec![],
            &vec![],
            &HashMap::<&str, &str>::new(),
            false,
            logger,
            vec![
                "bash",
                "-c",
                &self.state.command_pkg_download.replace(PLACEHOLDER_PACKAGE, package.as_ref()),
            ],
        )?;

        if exit_code != 0 {
            return Err(RootFSError::DownloadPackage {
                name: package.as_ref().to_string(),
            });
        }

        Ok(())
    }

    fn install_native_package(
        &self,
        install_path: impl AsRef<Path>,
        work_path: impl AsRef<Path>,
        package: impl AsRef<str>,
        logger: &mut dyn Write,
    ) -> Result<(), RootFSError> {
        let exit_code = runtime_execute(
            self.sub_path(RootFSPath::Fs),
            true,
            self.state.root_uid,
            self.state.root_gid,
            "/",
            &vec![&Mount {
                dest: PathBuf::new(),
                kind: MountKind::OverlayFS(Overlay {
                    upper_directory: Some(OverlayUpperDirectory {
                        upper_directory: install_path.as_ref().to_path_buf(),
                        work_directory: work_path.as_ref().to_path_buf(),
                    }),
                    lower_directories: vec![self.sub_path(RootFSPath::Fs)],
                }),
            }],
            &vec![],
            &HashMap::<&str, &str>::new(),
            false,
            logger,
            vec!["bash", "-c", format!("apt-get install -y --no-download {}", package.as_ref()).as_str()],
        )?;

        if exit_code != 0 {
            return Err(RootFSError::InstallPackage {
                name: package.as_ref().to_string(),
            });
        }

        return Ok(());
    }

    pub fn exec(
        &self,
        cwd: impl AsRef<Path>,
        mounts: &Vec<&Mount>,
        environment: &HashMap<impl AsRef<str>, impl AsRef<str>>,
        logger: &mut dyn Write,
        args: Vec<impl AsRef<str>>,
        pkgset: &Option<CachedPkgSet>,
    ) -> Result<i32, RuntimeError> {
        let mut lower_mounts = Vec::new();
        if let Some(pkgset) = pkgset {
            lower_mounts.push(Mount {
                dest: PathBuf::new(),
                kind: MountKind::OverlayFS(Overlay {
                    upper_directory: None,
                    lower_directories: vec![self.sub_path(RootFSPath::Fs), pkgset.path()],
                }),
            });
        }

        runtime_execute(
            self.sub_path(RootFSPath::Fs),
            true,
            self.state.user_uid,
            self.state.user_gid,
            cwd,
            &lower_mounts.iter().collect(),
            mounts,
            environment,
            false,
            logger,
            args,
        )
    }
}
