use std::{
    collections::HashSet,
    fs::{exists, read_to_string, write},
    path::Path,
    str::FromStr,
};

use chariot_util::fs::FileSystemError;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::{ManifestFetchSpec, ROOTFS_VERSION};

const STATE_KEY_INTACT: &str = "intact";
const STATE_KEY_ROOTFS_VERSION: &str = "rootfs_version";

#[derive(Deserialize, Serialize)]
pub struct CachedManifest {
    pub root_packages: HashSet<String>,
    pub package_bsdtar: String,
    pub package_git: String,
    pub package_patch: String,

    pub command_pkg_download: String,
    pub command_pkg_install: String,

    pub user_uid: u32,
    pub user_gid: u32,
    pub root_uid: u32,
    pub root_gid: u32,
}

#[derive(Deserialize, Serialize)]
pub struct State {
    pub manifest: ManifestFetchSpec,
    pub cached_manifest: CachedManifest,
}

#[derive(Error, Debug)]
pub enum StateWriteError {
    #[error(transparent)]
    FileSystem(#[from] FileSystemError),

    #[error(transparent)]
    TomlSerialize(#[from] toml::ser::Error),
}

#[derive(Error, Debug)]
pub enum StateReadError {
    #[error(transparent)]
    FileSystem(#[from] FileSystemError),

    #[error(transparent)]
    TomlDeserialize(#[from] toml::de::Error),

    #[error("RootFS state is missing or has an invalid version")]
    InvalidVersion,

    #[error("RootFS version mismatch, expected `{}`, got `{}`", expected, found)]
    RootFSVersionMismatch { expected: i64, found: i64 },
}

impl State {
    pub fn read(path: impl AsRef<Path>) -> Result<Option<Self>, StateReadError> {
        if !exists(&path).map_err(|err| FileSystemError::Exists {
            path: path.as_ref().to_path_buf(),
            source: err,
        })? {
            return Ok(None);
        }

        let data = read_to_string(&path).map_err(|err| FileSystemError::ReadFile {
            path: path.as_ref().to_path_buf(),
            source: err,
        })?;

        let table = toml::Table::from_str(&data)?;

        let intact = match table.get(STATE_KEY_INTACT).and_then(|v| v.as_bool()) {
            None => false,
            Some(intact) => intact,
        };

        if !intact {
            return Ok(None);
        }

        let rootfs_version = match table.get(STATE_KEY_ROOTFS_VERSION).and_then(|v| v.as_integer()) {
            None => return Err(StateReadError::InvalidVersion),
            Some(version) => version,
        };

        if rootfs_version != ROOTFS_VERSION {
            return Err(StateReadError::RootFSVersionMismatch {
                expected: ROOTFS_VERSION,
                found: rootfs_version,
            });
        }

        let state = table.try_into::<Self>()?;

        Ok(Some(state))
    }

    pub fn write(&self, dest: impl AsRef<Path>, intact: bool) -> Result<(), StateWriteError> {
        let mut table = toml::Table::try_from(self)?;

        table.insert(String::from(STATE_KEY_ROOTFS_VERSION), toml::Value::Integer(ROOTFS_VERSION));
        table.insert(String::from(STATE_KEY_INTACT), toml::Value::Boolean(intact));

        let data = format!("# Generated by chariot. DONT TOUCH!\n{}", toml::to_string(&table)?);

        write(&dest, data).map_err(|err| FileSystemError::WriteFile {
            path: dest.as_ref().to_path_buf(),
            source: err,
        })?;

        Ok(())
    }
}
